spring:
  application:
    name: Loan Approval Process

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    clean-disabled: true

loan:
  customer:
    max-age: ${LOAN_CUSTOMER_MAX_AGE}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
